project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
branch: main
base_path: .
preserve_hierarchy: 1
files:
  - source: /locales/zh_HK/*.ts
    translation: /locales/%locale%/%file_name%
    multilingual: 1
  - source: /locales/zh_HK/figma.json
    translation: /locales/%three_letters_code%/figma.json
    multilingual: 1
    update_option: update_as_unapproved
